import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import {useState, useEffect} from 'react'
//import styles from '../styles/desktop-1.css'
//import bg from 'img/header-hero.jpg'

const inter = Inter({ subsets: ['latin'] })

export default function Home({benefit, head, talent, company, community, protocolDet, testimonial, partnership}) {

const [mounted, setMounted] = useState(false);
  useEffect(() => {
      setMounted(true)
  }, [])

  return (
    mounted && <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

    <script src="js/vendor/jquery-1.12.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="js/vendor/modernizr-3.7.1.min.js"></script>
    
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    
    <script src="js/slick.min.js"></script>
    
    <script src="js/imagesloaded.pkgd.min.js"></script>
    <script src="js/isotope.pkgd.min.js"></script>
    
    <script src="js/waypoints.min.js"></script>
    <script src="js/jquery.counterup.min.js"></script>
    
    <script src="js/circles.min.js"></script>
    
    <script src="js/jquery.appear.min.js"></script>
    
    <script src="js/wow.min.js"></script>
    
    <script src="js/headroom.min.js"></script>
    
    <script src="js/jquery.nav.js"></script>
    
    <script src="js/scrollIt.min.js"></script>
    
    <script src="js/jquery.magnific-popup.min.js"></script>
    
    <script src="js/main.js"></script>
      </Head>

      <body>
      <div className="blobs">
        <svg width="1352" height="1621" viewBox="0 0 1352 1621" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path fillRule="evenodd" clipRule="evenodd" d="M467.008 160.875C489.446 166.457 507.528 183.997 519.982 206.529C532.332 228.872 542.143 256.78 536.019 285.729C530.197 313.255 502.518 326.014 489.491 350.672C474.692 378.684 478.606 420.471 455.595 437.959C432.868 455.231 405.265 443.167 383.794 430.999C364.578 420.109 356.064 395.073 343.533 374.451C330.542 353.072 311.142 336.463 309.264 308.346C307.261 278.336 316.045 244.985 333.208 219.814C349.879 195.366 375.517 186.902 399.182 176.477C421.868 166.484 445.118 155.43 467.008 160.875Z" fill="#00A99C" fillOpacity="0.08"/>
        <path fillRule="evenodd" clipRule="evenodd" d="M518.076 499.484C516.998 504.86 515.077 510.854 509.344 512.546C503.609 514.238 496.539 509.891 489.98 507.775C483.72 505.755 476.797 504.959 471.979 500.489C467.112 495.974 464.854 489.8 464.675 484.3C464.513 479.311 468.328 475.962 471.058 472.136C473.56 468.628 475.82 465.063 479.896 462.965C484.657 460.516 490.02 457.047 496.118 459.241C502.236 461.443 504.75 468.167 508.383 473.217C511.196 477.128 513.266 481.028 514.821 485.242C516.609 490.086 518.979 494.987 518.076 499.484Z" fill="#D8ECEC"/>
        <path fillRule="evenodd" clipRule="evenodd" d="M219.077 407.204C273.689 417.249 283.677 466.067 326.991 490.144C365.087 511.319 427.812 509.681 453.81 537.68C481.835 567.861 479.826 606.494 466.906 640.824C453.304 676.967 426.476 712.302 380.07 733.62C334.086 754.745 273.61 763.301 219.077 754.675C169.376 746.813 144.65 712.248 105.971 690.262C71.7717 670.823 22.1334 661.162 5.79381 633.44C-10.8336 605.23 12.8302 575.251 20.6039 545.43C30.0571 509.167 17.7309 467.068 56.1361 440.321C96.1501 412.453 162.957 396.88 219.077 407.204Z" fill="#00A99C" fillOpacity="0.13"/>
        <path fillRule="evenodd" clipRule="evenodd" d="M1004.43 113.15C1013.83 112.625 1024.01 113.273 1030.79 118.485C1037.65 123.757 1037.98 131.902 1038.68 139.473C1039.45 147.932 1042.67 157.927 1034.94 163.767C1027.26 169.575 1015.03 165.248 1004.43 165.359C993.574 165.473 981.854 169.548 973.113 164.414C963.681 158.875 958.558 148.694 960.356 139.473C962.014 130.968 972.884 126.399 981.531 121.235C988.477 117.088 995.774 113.633 1004.43 113.15Z" fill="#00FFFF" fillOpacity="0.2"/>
        <path fillRule="evenodd" clipRule="evenodd" d="M1037.48 197.067C1041 196.528 1044.08 199.329 1046.66 201.899C1049.32 204.552 1052.29 207.675 1051.98 211.51C1051.67 215.223 1048.15 217.491 1045.22 219.61C1042.92 221.274 1040.27 222.046 1037.48 221.998C1034.74 221.951 1031.87 221.435 1029.99 219.349C1028.15 217.306 1027.9 214.315 1028.03 211.51C1028.14 208.857 1029.2 206.541 1030.63 204.35C1032.55 201.43 1034.13 197.579 1037.48 197.067Z" fill="#00A99C" fillOpacity="0.15"/>
        <path fillRule="evenodd" clipRule="evenodd" d="M1184.28 8.40872C1221.3 11.5702 1259.26 15.0411 1286.36 36.6607C1314.19 58.8684 1333.36 91.0988 1328.14 123.199C1323.32 152.888 1286.41 167.402 1261.64 188.782C1236.45 210.518 1219.92 243.447 1184.28 247.351C1146.34 251.508 1104.95 235.365 1083.97 208.244C1064.88 183.582 1091.98 152.52 1088.2 123.199C1083.37 85.7501 1033.62 47.9967 1059.34 17.2743C1084.48 -12.7645 1141.05 4.71723 1184.28 8.40872Z" fill="#D0E9E9" fillOpacity="0.74"/>
        <path fillRule="evenodd" clipRule="evenodd" d="M719.677 253.379C843.687 241.5 1008.47 199.254 1052.04 314.559C1097.32 434.387 961.886 534.018 850.115 598.583C773.341 642.933 681.133 623.059 610.574 569.576C546.224 520.799 513.939 439.441 540.107 363.6C565.243 290.753 642.13 260.808 719.677 253.379Z" fill="#C4C4C4" fillOpacity="0.71"/>
        <path fillRule="evenodd" clipRule="evenodd" d="M455.571 833.053C503.361 833.627 554.815 841.307 583.219 875.423C610.779 908.527 603.973 953.902 588.485 992.7C575.285 1025.77 543.72 1047.4 508.333 1063.02C472.18 1078.98 430.75 1094.11 394.501 1078.33C358.45 1062.63 350.91 1023.44 339.167 989.356C325.548 949.826 297.84 906.791 323.522 872.307C350.452 836.146 406.738 832.467 455.571 833.053Z" fill="#00A99C" fillOpacity="0.14"/>
        <path fillRule="evenodd" clipRule="evenodd" d="M1203.54 1356.57C1238.54 1360.01 1271.8 1368.98 1298.13 1390.15C1326.33 1412.82 1354 1441.74 1351.89 1475.84C1349.82 1509.04 1313.67 1528.6 1288.05 1552.4C1261.87 1576.73 1240.1 1606.1 1203.54 1613.66C1157.73 1623.12 1101.62 1628.37 1069.1 1597.64C1036.75 1567.06 1054.6 1518.1 1057.71 1475.84C1060.5 1437.95 1054.79 1394.72 1085.91 1369.27C1116.38 1344.35 1162.73 1352.55 1203.54 1356.57Z" fill="#063C4D" fillOpacity="0.08"/>
        <path fillRule="evenodd" clipRule="evenodd" d="M535.094 724.118C545.305 725.048 551.261 734.055 557.851 741.484C564.779 749.293 573.722 756.631 572.954 766.796C572.061 778.61 565.052 790.113 553.784 795.301C542.467 800.511 529.256 797.491 518.051 792.071C507.236 786.84 498.024 778.397 495.589 767.151C493.211 756.17 498.303 745.233 506.076 736.766C513.42 728.767 523.939 723.101 535.094 724.118Z" fill="#00FFFF" fillOpacity="0.21"/>
        </svg>
      </div>
        {/*}
      <div className="preloader">
        <div className="loader">
            <div className="ytp-spinner">
                <div className="ytp-spinner-container">
                    <div className="ytp-spinner-rotator">
                        <div className="ytp-spinner-left">
                            <div className="ytp-spinner-circle"></div>
                        </div>
                        <div className="ytp-spinner-right">
                            <div className="ytp-spinner-circle"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
  </div>*/}

    {/*<!--====== PRELOADER PART ENDS ======-->*/}
    
    {/*<!--====== HEADER PART START ======-->*/}
    
    <header className="header-area">
        <div className="navbar-area headroom">
            <div className="container">
                <div className="row">
                    <div className="col-lg-12">
                        <nav className="navbar navbar-expand-lg">
                            <a className="navbar-brand col-lg-3" href="index.html">
                                <img src="img/dar-logo.png" alt="Logo"/>
                            </a>
                            <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                <span className="toggler-icon"></span>
                                <span className="toggler-icon"></span>
                                <span className="toggler-icon"></span>
                            </button>

                            <div className="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
                                <ul  className="navbar-nav m-auto">
                                    <li className="nav-item active">
                                        <a href="#home">Home</a>
                                    </li>
                                    <li className="nav-item">
                                        <a href="#about">What we do</a>
                                    </li>
                                    <li className="nav-item">
                                        <a href="#services">Our Services</a>
                                    </li>
                                    <li className="nav-item">
                                        <a href="#protocol">Our Protocol</a>
                                    </li>
                                    <li className="nav-item">
                                        <a href="#contact">Contact us</a>
                                    </li>
                                    {/*
                                    <li className="nav-item">
                                        <a href="#contact">Contact</a>
                                    /li>*/}
                                </ul>
                            </div> {/*<!-- navbar collapse -->*/}
                            
                            <div className="navbar-btn d-none d-sm-inline-block">
                                <a className="main-btn" data-scroll-nav="0" target="_blank" href="https://discord.gg/darshana">Join our Community</a>
                            </div>
                        </nav> {/*<!-- navbar -->*/}
                    </div>
                </div> {/*<!-- row -->*/}
            </div> {/*<!-- container -->*/}
        </div> {/*<!-- navbar area -->*/}
        
        <div id="home" className="header-hero bg_cover d-lg-flex align-items-center">
          {/* style={{
      backgroundImage: `url(${bg.src})`,
      width: '100%',
      height: '100%',
    }} */}
            <div className="container">
                <div className="row">
                    <div className="col-lg-7">
                        <div className="header-hero-content">
                            <h1 className="hero-title wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.2s"><b><span className="changing-text"></span></b><br/><b>the future of work</b></h1>
                            {head.data.map ( he => ( 
                                he.status === "published" &&
                                <p className="text wow fadeInUp" key={he.id} data-wow-duration="1s" data-wow-delay="0.5s">{he.text}</p>
                                
                            ))}
                            {/*<p className="text wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.5s">Phasellus vel elit efficitur, gravida libero sit amet, scelerisque  tortor arcu, commodo sit amet nulla sed.</p>*/}
                            
                            <div className="header-singup wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.8s">
                            <a href="https://app.darshana.io/" target="_blank"><button className="main-btn light-btn">Find a job</button></a>
                            <a href="https://api.whatsapp.com/send?phone=51982255435&text=Hi!%20I%20would%20like%20to%20schedule%20a%20demo%20for%20hiring%20tech%20talent.%20/%20Hola!%20Me%20gustar%C3%ADa%20agendar%20un%20demo%20para%20contratar%20talento%20tech." target="_blank"><button className="main-btn dark-btn">Request a demo</button></a>
                            </div>
                        </div> {/*<!-- header hero content -->*/}
                    </div>
                </div> {/*<!-- row -->*/}
            </div> {/*<!-- container -->*/}
            <div className="header-hero-image d-flex align-items-center wow fadeInRightBig" data-wow-duration="1s" data-wow-delay="1.1s">
                <div className="image">
                    <img src="img/person-learning.png" alt="Hero Image"/>
                </div>
            </div> {/*<!-- header hero image -->*/}
        </div> {/*<!-- header hero -->*/}
    </header>


    
    {/*<!--====== HEADER PART ENDS ======-->*/}
    
    {/*<!--====== ABOUT PART START ======-->*/}
    
    <section id="about" className="about-area pt-115">
        <div className="container">
            <div className="row justify-content-center">
                <div className="col-lg-9">
                    <div className="about-title text-center wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.3s">
                        <h6 className="welcome">WELCOME</h6>
                        <h3 className="title">There are multiple <span>benefits of working with Darshana.</span></h3>
                    </div>
                </div>
            </div> {/*<!-- row -->*/}
            <div className="row align-items-center">
                <div className="col-lg-5">
                    <div className="about-image mt-60 wow fadeIn text-center" data-wow-duration="1s" data-wow-delay="0.5s">
                        <img src="img/person-about.png" alt="about"/>
                    </div> {/*<!-- about image -->*/}
                </div>
                <div className="col-lg-7">
                    <div className="about-image mt-60 wow fadeIn benefits" data-wow-duration="1s" data-wow-delay="0.5s">                    
                    {benefit.data.map (ben => (
                        ben.status === 'published' &&

                    <div className="benefit row" key={ben.id}>
                    <img className="stars-1" src="img/stars-1-1@2x.png" alt="stars 1" />
                    <div className="talent-container col-10">
                      <h4>
                      {ben.title}
                      </h4>
                      <p className="find-the-best-talent roboto-medium-tarawera-20px">
                      {ben.description}
                      </p>
                    </div>
                    </div>

                    ))}
                      
                    </div> {/*<!-- End of benefits -->*/}
                    <div className="row justify-content-lg-center mt-45">
                      <a href="https://app.darshana.io/" target="_blank"><button className="main-btn light-btn text-center">Start Now</button></a>
                    </div>
                </div>
            </div> {/*<!-- row -->*/}
            {/* Contadores y texto */}
            {/*}
            <div className="row justify-content-center">
                <div className="col-lg-10">
                    <div className="about-content pt-45">
                        <p className="text wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.4s">Duis et metus et massa tempus lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas ultricies, orci molestie blandit interdum. ipsum ante pellentesque nisl, eget mollis turpis quam nec eros. ultricies, orci molestie blandit interdum.</p>
                        
                        <div className="about-counter pt-60">
                            <div className="row">
                                <div className="col-sm-4">
                                    <div className="single-counter counter-color-1 mt-30 d-flex wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.3s">
                                        <div className="counter-shape">
                                            <span className="shape-1"></span>
                                            <span className="shape-2"></span>
                                        </div>
                                        <div className="counter-content media-body">
                                            <span className="counter-count"><span className="counter">350</span></span>
                                            <p className="text">Clients</p>
                                        </div>
                                    </div> <!-- single counter -->
                                </div>
                                <div className="col-sm-4">
                                    <div className="single-counter counter-color-2 mt-30 d-flex wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.6s">
                                        <div className="counter-shape">
                                            <span className="shape-1"></span>
                                            <span className="shape-2"></span>
                                        </div>
                                        <div className="counter-content media-body">
                                            <span className="counter-count"><span className="counter">99</span>%</span>
                                            <p className="text">Satisfaction</p>
                                        </div>
                                    </div> {/*<!-- single counter -->
                                </div>
                                <div className="col-sm-4">
                                    <div className="single-counter counter-color-3 mt-30 d-flex wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.9s">
                                        <div className="counter-shape">
                                            <span className="shape-1"></span>
                                            <span className="shape-2"></span>
                                        </div>
                                        <div className="counter-content media-body">
                                            <span className="counter-count"><span className="counter">870</span></span>
                                            <p className="text">Projects</p>
                                        </div>
                                    </div> {/*<!-- single counter -->
                                </div>
                            </div> {/*<!-- row -->
                        </div> {/*<!-- about counter -->
                    </div> {/*<!-- about content -->
                </div>
            </div> {/*<!-- row -->    */}
            {/* Fin de Contadores y texto */}
        </div> {/*<!-- container -->*/}
    </section>
    
    {/*<!--====== ABOUT PART ENDS ======-->*/}
    
    {/*<!--====== OUR SERVICE PART START ======-->*/}
    
    <section id="services" className="our-services-area pt-115">
        <div className="container">
            <div className="row justify-content-center">
                <div className="col-xl-5 col-lg-6 col-md-8 col-sm-9">
                    <div className="section-title text-center wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.2s">
                        <h6 className="sub-title">Our services</h6>
                        <h4 className="title">We bring solutions <span>for different types of profiles</span></h4>
                    </div> {/*<!-- section title -->*/}
                </div>
            </div> {/*<!-- row -->*/}
            <div className="row">
                <div className="col-lg-12">
                    <div className="our-services-tab pt-30">
                        <ul className="nav justify-content-center wow fadeIn" data-wow-duration="1s" data-wow-delay="0.5s" id="myTab" role="tablist">
                            <li className="nav-item">
                                <a className="active" id="business-tab" data-toggle="tab" href="#business" role="tab" aria-controls="business" aria-selected="true">
                                    <i className="lni-briefcase"></i> <span>Talent</span>
                                </a>
                            </li>
                            <li className="nav-item">
                                <a id="digital-tab" data-toggle="tab" href="#digital" role="tab" aria-controls="digital" aria-selected="false">
                                    <i className="lni-bullhorn"></i> <span>Company</span>
                                </a>
                            </li>

                            <li className="nav-item">
                                <a id="market-tab" data-toggle="tab" href="#market" role="tab" aria-controls="market" aria-selected="false">
                                    <i className="lni-stats-up"></i> <span>Community</span>
                                </a>
                            </li>
                        </ul>
                        <div className="tab-content" id="myTabContent">
                            <div className="tab-pane fade show active" id="business" role="tabpanel" aria-labelledby="business-tab">
                                <div className="row">
                                    <div className="col-lg-6">
                                        <div className="our-services-image mt-50">
                                            <img src="img/talent.png" alt="service"/>
                                        </div> {/*<!-- our services image -->*/}
                                    </div>
                                    <div className="col-lg-6">
                                        <div className="our-services-content mt-45">
                                            <h3 className="services-title"><span>I'm a Talent</span> looking for a job.</h3>
                                            <p className="text">
                                                <ul className="benefit-list">
                                                    { talent.data.map (tal =>(
                                                        tal.status === 'published' &&
                                                        <li key={tal.id}>{tal.text}</li>
                                                    ))}
                                                </ul>
                                            </p>
                                            {/*<div className="questions">
                                                <h4>Frequent questions</h4>


                                                    </div>*/}
                                            {/*}
                                            <div className="our-services-progress d-flex align-items-center mt-55">
                                                <div className="circle" id="circles-1"></div>
                                                <div className="progress-content">
                                                    <h4 className="progress-title">Consultancy<br/> Agency Skill.</h4>
                                                </div>
                                            </div>
                                            */}
                                        </div> {/*<!-- our services content -->*/}
                                    </div>
                                </div> {/*<!-- row -->*/}
                            </div>
                            
                            <div className="tab-pane fade" id="digital" role="tabpanel" aria-labelledby="digital-tab">
                                <div className="row">
                                    <div className="col-lg-6">
                                        <div className="our-services-image mt-50">
                                            <img src="img/company.png" alt="service"/>
                                        </div> {/*<!-- our services image -->*/}
                                    </div>
                                    <div className="col-lg-6">
                                        <div className="our-services-content mt-45">
                                            <h3 className="services-title"><span>I'm a company</span> looking to hire digital talent.</h3>
                                            <p className="text">
                                            <ul className="benefit-list">
                                                    { company.data.map (comp =>(
                                                        comp.status === 'published' &&
                                                        <li key={comp.id}>{comp.text}</li>
                                                    ))}
                                            </ul>
                                            </p>
                                            
                                        
                                        </div> {/*<!-- our services content -->*/}
                                    </div>
                                </div> {/*<!-- row -->*/}
                            </div>
                            
                            <div className="tab-pane fade" id="market" role="tabpanel" aria-labelledby="market-tab">
                                <div className="row">
                                    <div className="col-lg-6">
                                        <div className="our-services-image mt-50">
                                            <img src="img/community.png" alt="service"/>
                                        </div> {/*<!-- our services image -->*/}
                                    </div>
                                    <div className="col-lg-6">
                                        <div className="our-services-content mt-45">
                                            <h3 className="services-title"><span>I'm part of a community</span> seeking to connect with digital talent.</h3>
                                            <p className="text">
                                            <ul className="benefit-list">
                                                    { community.data.map (comu =>(
                                                        comu.status === 'published' &&
                                                        <li key={comu.id}>{comu.text}</li>
                                                    ))}
                                            </ul>
                                            </p>
                                            
                                        
                                        </div> {/*<!-- our services content -->*/}
                                    </div>
                                </div> {/*<!-- row -->*/}
                            </div>
                        </div> {/*<!-- tab content -->*/}
                    </div> {/*<!-- our services tab -->*/}
                </div>
            </div> {/*<!-- row -->*/}
        </div> {/*<!-- container -->*/}
    </section>
    
    {/*<!--====== OUR SERVICE PART ENDS ======-->*/}
    
    {/*<!--====== SERVICE PART START ======-->*/}
    
    <section id="protocol" className="service-area pt-105 pb-100">
        <div className="container">
            <div className="row">
                <div className="col-lg-6 col-md-8">
                    <div className="section-title wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.2s">
                        <h6 className="sub-title">What makes us different</h6>
                        <h4 className="title"><span>Our sovereign work</span> Identity Protocol</h4>
                    </div> {/*<!-- section title -->*/}
                </div>
            </div> {/*<!-- row -->*/}
            <div className="service-wrapper mt-60 wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.6s">
                <div className="row no-gutters justify-content-center">
                { protocolDet.data.map (pro =>(
                    pro.status === 'published' &&
                    
                    <div className="col-lg-4 col-md-7" key={pro.id}>
                        <div className="single-service d-flex">
                            <div className="service-icon">
                                    <img src={"https://darshana.directus.app/assets/" + pro.icon} alt="Icon"/>
                            </div>
                            <div className="service-content media-body">
                                    <h4 className="service-title">{pro.title}</h4>
                                    <p className="text">{pro.description}</p>
                            </div>
                        </div>
                    </div>

                                                    ))}
                    {/*
                    <div className="col-lg-4 col-md-7">
                        <div className="single-service d-flex">
                            <div className="service-icon">
                                <img src="img/service-1.png" alt="Icon"/>
                            </div>
                            <div className="service-content media-body">
                                <h4 className="service-title">Validate and record your work experience on the blockchain</h4>
                                <p className="text">Lorem Ipsum is simply dummy tex of the printing.</p>
                            </div>
                            <div className="shape shape-1">
                                <img src="img/shape/shape-1.svg" alt="shape"/>
                            </div>
                            <div className="shape shape-2">
                                <img src="img/shape/shape-2.svg" alt="shape"/>
                            </div>
                        </div> {/*<!-- single service -->
                    </div>
                    <div className="col-lg-4 col-md-7">
                        <div className="single-service service-border d-flex">
                            <div className="service-icon">
                                <img src="img/service-2.png" alt="Icon"/>
                            </div>
                            <div className="service-content media-body">
                                <h4 className="service-title">Manage your own sovereign identity</h4>
                                <p className="text">Lorem Ipsum is simply dummy tex.</p>
                            </div>
                            <div className="shape shape-3">
                                <img src="img/shape/shape-3.svg" alt="shape"/>
                            </div>
                        </div> {/*<!-- single service -->
                    </div>
                    <div className="col-lg-4 col-md-7">
                        <div className="single-service d-flex">
                            <div className="service-icon">
                                <img src="img/service-3.png" alt="Icon"/>
                            </div>
                            <div className="service-content media-body">
                                <h4 className="service-title">Reliable sources that validate your skills when applying for jobs</h4>
                                <p className="text">Lorem Ipsum is simply dummy tex of the printing.</p>
                            </div>
                            <div className="shape shape-4">
                                <img src="img/shape/shape-4.svg" alt="shape"/>
                            </div>
                            <div className="shape shape-5">
                                <img src="img/shape/shape-5.svg" alt="shape"/>
                            </div>
                        </div> {/*<!-- single service -->
                    </div> */}
                </div> {/*<!-- row -->*/}
                <div className="row">
                    <div className="col-lg-12">
                        <div className="service-btn text-center pt-25 pb-15">
                            <a className="main-btn main-btn-2" href="#">Read our whitepaper</a>
                        </div> {/*<!-- service btn -->*/}
                    </div>
                </div> {/*<!-- row -->*/}
            </div> {/*<!-- service wrapper -->*/}
        </div> {/*<!-- container -->*/}
    </section>

    {/* NEWSLETTER SECTION */}

    <section id="newsletter" className="about-area pt-80 pb-80">
        <div className="container">
            <div className="row justify-content-center">
                <div className="col-lg-9">
                    <div className="about-title text-center wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.3s">
                        <h6 className="welcome">SUBSCRIBE TO OUR NEWSLETTER</h6>
                        <h3 className="title">Stay up-to-date with the latest job opportunities and web3 advancements <span>- subscribe now!</span></h3>
                    </div>
                </div>
            </div> {/*<!-- row -->*/}
            <div className="row align-items-center">
                <div className="col-lg-12">
                    <div className="about-image mt-60 wow fadeIn text-center" data-wow-duration="1s" data-wow-delay="0.5s">
                        <div className="header-hero-content">
                                
                                <div className="header-singup wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.8s">
                                    <input type="text" placeholder="username@yourdomain.com"/>
                                    <button className="main-btn newsletter-btn">Subscribe</button>
                                </div>
                        </div>
                    </div> {/*<!-- about image -->*/}
                </div>
                
            </div> {/*<!-- row -->*/}

        </div> {/*<!-- container -->*/}
    </section>                 

    {/*<!--====== SERVICE PART ENDS ======-->*/}
    
    {/*<!--====== PROJECT GALLERY PART START ======-->*/}
{/*}
    <section id="" className="project-masonry-area pt-115">
        <div className="container">
            <div className="row align-items-end">
                <div className="col-lg-4">
                    <div className="section-title pb-20  wow fadeIn" data-wow-duration="1s" data-wow-delay="0.4s">
                        <h6 className="sub-title">Portfolio</h6>
                        <h4 className="title">Portfolio <span>Gallery.</span></h4>
                    </div> {/*<!-- section title -->*
                </div>
                <div className="col-lg-8">
                    <div className="project-menu text-center text-sm-left text-lg-right pb-20">
                        <ul>
                            <li className="active" data-filter="*">See All</li>
                            <li data-filter=".apps">Apps</li>
                            <li data-filter=".branding">Branding</li>
                            <li data-filter=".creative">Creative</li>
                            <li data-filter=".laptop">Laptop</li>
                            <li data-filter=".product">Product</li>
                        </ul>
                    </div> {/*<!-- project menu -->
                </div>
            </div> {/*<!-- row -->
            <div className="row grid">
                <div className="col-lg-4 col-sm-6 grid-item apps creative laptop">
                    <div className="single-gallery gallery-masonry mt-30">
                        <div className="gallery-image">
                            <img src="img/protfolio-1.jpg" alt="protfolio"/>
                        </div>
                        <div className="gallery-icon">
                            <a className="image-popup" href="assets/images/protfolio-1.jpg">
                                <span></span>
                            </a>
                        </div>
                    </div> {/*<!-- single gallery -->
                </div>
                <div className="col-lg-4 col-sm-6 grid-item branding creative">
                    <div className="single-gallery gallery-masonry mt-30">
                        <div className="gallery-image">
                            <img src="img/protfolio-2.jpg" alt="protfolio"/>
                        </div>
                        <div className="gallery-icon">
                            <a className="image-popup" href="assets/images/protfolio-2.jpg">
                                <span></span>
                            </a>
                        </div>
                    </div> {/*<!-- single gallery -->
                </div>
                <div className="col-lg-4 col-sm-6 grid-item apps branding product">
                    <div className="single-gallery gallery-masonry mt-30">
                        <div className="gallery-image">
                            <img src="img/protfolio-3.jpg" alt="protfolio"/>
                        </div>
                        <div className="gallery-icon">
                            <a className="image-popup" href="assets/images/protfolio-3.jpg">
                                <span></span>
                            </a>
                        </div>
                    </div> {/*<!-- single gallery -->
                </div>
                <div className="col-lg-4 col-sm-6 grid-item laptop product">
                    <div className="single-gallery gallery-masonry mt-30">
                        <div className="gallery-image">
                            <img src="img/protfolio-5.jpg" alt="protfolio"/>
                        </div>
                        <div className="gallery-icon">
                            <a className="image-popup" href="assets/images/protfolio-5.jpg">
                                <span></span>
                            </a>
                        </div>
                    </div> {/*<!-- single gallery -->
                </div>
                <div className="col-lg-4 col-sm-6 grid-item branding creative">
                    <div className="single-gallery gallery-masonry mt-30">
                        <div className="gallery-image">
                            <img src="img/protfolio-4.jpg" alt="protfolio"/>
                        </div>
                        <div className="gallery-icon">
                            <a className="image-popup" href="assets/images/protfolio-4.jpg">
                                <span></span>
                            </a>
                        </div>
                    </div> {/*<!-- single gallery -->
                </div>
                <div className="col-lg-4 col-sm-6 grid-item apps laptop product">
                    <div className="single-gallery gallery-masonry mt-30">
                        <div className="gallery-image">
                            <img src="img/protfolio-6.jpg" alt="protfolio"/>
                        </div>
                        <div className="gallery-icon">
                            <a className="image-popup" href="assets/images/protfolio-6.jpg">
                                <span></span>
                            </a>
                        </div>
                    </div> {/*<!-- single gallery -->
                </div>
            </div> {/*<!-- row -->
            <div className="row">
                <div className="col-lg-12">
                    <div className="gallery-btn mt-60 text-center">
                        <a className="main-btn" href="#">Load More</a>
                    </div>
                </div>
            </div> {/*<!-- row -->
        </div> {/*<!-- container -->
    </section>

    {/*<!--====== PROJECT GALLERY PART ENDS ======-->*/}
    
    {/*<!--====== PRICING PART START ======-->*/}
    
    {/*}
    <section data-scroll-index="0" id="pricing" className="pricing-area pt-115">
        <div className="container">
            <div className="row justify-content-center">
                <div className="col-lg-5 col-md-8 col-sm-9">
                    <div className="section-title text-center pb-20 wow fadeInUpBig" data-wow-duration="1s" data-wow-delay="0.2s">
                        <h6 className="sub-title">Pricing Plans</h6>
                        <h4 className="title">Providing Best Pricing <span>For Your Business.</span></h4>
                    </div> {/*<!-- section title -->
                </div>
            </div> {/*<!-- row -->
            <div className="row no-gutters justify-content-center">
                <div className="col-lg-4 col-md-7 col-sm-9">
                    <div className="single-pricing text-center pricing-color-1 mt-30 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.3s">
                        <div className="pricing-price">
                            <span className="price"><b>50</b>/m.<span className="symbol">$</span></span>
                        </div>
                        <div className="pricing-title mt-20">
                            <span className="btn">20% Off</span>
                            <h4 className="title">Basic</h4>
                        </div>
                        <div className="pricing-list pt-20">
                            <ul>
                                <li>Full Access</li>
                                <li>Unlimited Bandwidth</li>
                                <li>50 gb Space</li>
                                <li>1 Month Support</li>
                            </ul>
                        </div>
                        <div className="pricing-btn pt-70">
                            <a className="main-btn main-btn-2" href="#">Sign Up Now !</a>
                        </div>
                    </div> {/*<!-- single pricing -->
                </div>
                <div className="col-lg-4 col-md-7 col-sm-9">
                    <div className="single-pricing text-center pricing-active pricing-color-2 mt-30 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.6s">
                        <div className="pricing-price">
                            <span className="price"><b>69</b>/m.<span className="symbol">$</span></span>
                        </div>
                        <div className="pricing-title mt-20">
                            <span className="btn">Special</span>
                            <h4 className="title">Standard</h4>
                        </div>
                        <div className="pricing-list pt-20">
                            <ul>
                                <li>Full Access</li>
                                <li>Unlimited Bandwidth</li>
                                <li>50 gb Space</li>
                                <li>1 Month Support</li>
                            </ul>
                        </div>
                        <div className="pricing-btn pt-70">
                            <a className="main-btn" href="#">Sign Up Now !</a>
                        </div>
                    </div> {/*<!-- single pricing -->
                </div>
                <div className="col-lg-4 col-md-7 col-sm-9">
                    <div className="single-pricing text-center pricing-color-3 mt-30 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.9s">
                        <div className="pricing-price">
                            <span className="price"><b>99</b>/m.<span className="symbol">$</span></span>
                        </div>
                        <div className="pricing-title mt-20">
                            <span className="btn">New</span>
                            <h4 className="title">Premium</h4>
                        </div>
                        <div className="pricing-list pt-20">
                            <ul>
                                <li>Full Access</li>
                                <li>Unlimited Bandwidth</li>
                                <li>50 gb Space</li>
                                <li>1 Month Support</li>
                            </ul>
                        </div>
                        <div className="pricing-btn pt-70">
                            <a className="main-btn main-btn-2" href="#">Sign Up Now !</a>
                        </div>
                    </div> {/*<!-- single pricing -->
                </div>
            </div> {/*<!-- row -->
        </div> {/*<!-- container -->
    </section>
    
    {/*<!--====== PRICING PART ENDS ======-->*/}
    
    {/*<!--====== TESTIMONIAL PART START ======-->*/}
    
    <section id="testimonial" className="testimonial-area pt-70 pb-120">
        <div className="container">
            <div className="row justify-content-between">
                <div className="col-xl-5 col-lg-6">
                    <div className="testimonial-left-content mt-45 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.3s">
                        <div className="section-title">
                            <h6 className="sub-title">Testimonials</h6>
                            <h4 className="title">What our Community Says About Us</h4>
                        </div> {/*<!-- section title -->*/}
                        <ul className="testimonial-line">
                            <li></li>
                            <li></li>
                            <li></li>
                            <li></li>
                        </ul>
                        
                    </div> {/*<!-- testimonial left content -->*/}
                </div>
                <div className="col-lg-6">
                    <div className="testimonial-right-content mt-50 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.6s">
                        <div className="quota">
                            <i className="lni-quotation"></i>
                        </div>
                        <div className="testimonial-content-wrapper testimonial-active">
                        { testimonial.data.map (tes =>(
                            tes.status === 'published' &&
                            
                            <div className="single-testimonial" key={tes.id}>
                                <div className="testimonial-text">
                                    <p className="text">{tes.testimonial}</p>
                                </div>
                                <div className="testimonial-author d-sm-flex justify-content-between">
                                    <div className="author-info d-flex align-items-center">
                                        <div className="author-image">
                                            <img src={"https://darshana.directus.app/assets/" + tes.picture} alt="author"/>
                                        </div>
                                        <div className="author-name media-body">
                                            <h5 className="name">{tes.username}</h5>
                                            <span className="sub-title">{tes.type}</span>
                                        </div>
                                    </div>
                                    <div className="author-review">
                                        <ul className="star">
                                            <li><i className="lni-star"></i></li>
                                            <li><i className="lni-star"></i></li>
                                            <li><i className="lni-star"></i></li>
                                            <li><i className="lni-star"></i></li>
                                            <li><i className="lni-star"></i></li>
                                        </ul>
                                        {/*<span className="review">( 7 Reviews )</span>*/}
                                    </div>
                                </div>
                            </div>
                            ))}
                            
                        </div> {/*<!-- testimonial content wrapper -->*/}
                    </div> {/*<!-- testimonial right content -->*/}
                </div>
            </div> {/*<!-- row -->*/}
        </div> {/*<!-- container -->*/}
    </section>
    
    {/*<!--====== TESTIMONIAL PART ENDS ======-->*/}
    
    {/*<!--====== BRAND PART START ======-->*/}
    
    <div id="brand" className="brand-area">
        <div className="container">
            <div className="row">
                <div className="col-lg-12">
                    <div className="brand-wrapper pt-70 clearfix flex-wrap">
                    {partnership.data.map ( par => ( 
                        par.status === "published" &&
                        <div key={par.id} className="single-brand mt-50 text-md-left wow fadeIn" data-wow-duration="1s" data-wow-delay="0.3s">
                            <img src={"https://darshana.directus.app/assets/" + par.image} alt="Icon"/>
                        </div>
                    ))}

                        {/*}
                        <div className="single-brand mt-50 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.4s">
                            <img src="img/brand-3.png" alt="brand"/>
                        </div> {/*<!-- single brand -->*
                        <div className="single-brand mt-50 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.5s">
                            <img src="img/brand-4.png" alt="brand"/>
                        </div> {/*<!-- single brand -->
                        <div className="single-brand mt-50 text-md-right wow fadeIn" data-wow-duration="1s" data-wow-delay="0.6s">
                            <img src="img/brand-5.png" alt="brand"/>
                        </div> {/*<!-- single brand -->*/}
                    </div> {/*<!-- brand wrapper -->*/}
                </div>
            </div> {/*<!-- row -->*/}
        </div> {/*<!-- container -->*/}
    </div>
    
    {/*<!--====== BRAND PART ENDS ======-->*/}
    
    {/*<!--====== BLOG PART START ======-->*/}
    {/*}                                        
    <section id="blog" className="blog-area pt-115">
        <div className="container">
            <div className="row justify-content-center">
                <div className="col-lg-4">
                    <div className="section-title text-center pb-20 wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.3s">
                        <h6 className="sub-title">Our Blog</h6>
                        <h4 className="title">Letest <span>News.</span></h4>
                    </div> {/*<!-- section title -->
                </div>
            </div> {/*<!-- row -->
            <div className="row justify-content-center">
                <div className="col-lg-4 col-md-6 col-sm-8">
                    <div className="single-blog mt-30 wow fadeInUpBig" data-wow-duration="1s" data-wow-delay="0.4s">
                        <div className="blog-image">
                            <a href="blog-details.html"><img src="img/news-1.jpg" alt="news"/></a>
                        </div>
                        <div className="blog-content">
                            <h4 className="blog-title"><a href="blog-details.html">Nulla eget urna at tortor  turpi feugiat tristique in sit.</a></h4>
                            <div className="blog-author d-flex align-items-center">
                                <div className="author-image">
                                    <img src="img/author-1.jpg" alt="author"/>
                                </div>
                                <div className="author-content media-body">
                                    <h6 className="sub-title">Posted by</h6>
                                    <p className="text">Isabela Moreira</p>
                                </div>
                            </div>
                        </div>
                    </div> {/*<!-- single blog -->
                </div>
                <div className="col-lg-4 col-md-6 col-sm-8">
                    <div className="single-blog mt-30 wow fadeInUpBig" data-wow-duration="1s" data-wow-delay="0.7s">
                        <div className="blog-image">
                            <a href="blog-details.html"><img src="img/news-2.jpg" alt="news"/></a>
                        </div>
                        <div className="blog-content">
                            <h4 className="blog-title"><a href="blog-details.html">Nulla eget urna at tortor  turpi feugiat tristique in sit.</a></h4>
                            <div className="blog-author d-flex align-items-center">
                                <div className="author-image">
                                    <img src="img/author-2.jpg" alt="author"/>
                                </div>
                                <div className="author-content media-body">
                                    <h6 className="sub-title">Posted by</h6>
                                    <p className="text">Elon Musk</p>
                                </div>
                            </div>
                        </div>
                    </div> {/*<!-- single blog -->
                </div>
                <div className="col-lg-4 col-md-6 col-sm-8">
                    <div className="single-blog mt-30 wow fadeInUpBig" data-wow-duration="1s" data-wow-delay="1s">
                        <div className="blog-image">
                            <a href="blog-details.html"><img src="img/news-3.jpg" alt="news"/></a>
                        </div>
                        <div className="blog-content">
                            <h4 className="blog-title"><a href="blog-details.html">Nulla eget urna at tortor  turpi feugiat tristique in sit.</a></h4>
                            <div className="blog-author d-flex align-items-center">
                                <div className="author-image">
                                    <img src="img/author-3.jpg" alt="author"/>
                                </div>
                                <div className="author-content media-body">
                                    <h6 className="sub-title">Posted by</h6>
                                    <p className="text">Fiona</p>
                                </div>
                            </div>
                        </div>
                    </div> {/*<!-- single blog -->
                </div>
            </div> {/*<!-- row -->
        </div> {/*<!-- container -->
    </section>

    {/*<!--====== BLOG PART ENDS ======-->*/}
    
    {/*<!--====== CONTACT PART START ======-->*/}

    <section id="contact" className="contact-area pt-120 pb-120">
        <div className="container">
            <div className="row justify-content-center">
                <div className="col-lg-4">
                    <div className="section-title text-center pb-20 wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.3s">
                        <h6 className="sub-title">Our Contact</h6>
                        <h4 className="title">Get In <span>Touch.</span></h4>
                    </div> {/*<!-- section title -->*/}
                </div>
            </div> {/*<!-- row -->*/}
            <div className="contact-info pt-30">
                <div className="row">
                    <div className="col-lg-4 col-md-6">
                        <div className="single-contact-info contact-color-1 mt-30 d-flex  wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.3s">
                            <div className="contact-info-icon">
                                <i className="fa fa-map-marker" aria-hidden="true"></i>
                            </div>
                            <div className="contact-info-content media-body">
                                <p className="text">90 Canal St <br/>Boston, MA 02114 <br/>USA </p>
                            </div>
                        </div> {/*<!-- single contact info -->*/}
                    </div>
                    <div className="col-lg-4 col-md-6">
                        <div className="single-contact-info contact-color-2 mt-30 d-flex  wow fadeInUp align-items-center" data-wow-duration="1s" data-wow-delay="0.6s">
                            <div className="contact-info-icon">
                                <i className="fa fa-envelope" aria-hidden="true"></i>
                            </div>
                            <div className="contact-info-content media-body">
                                <p className="text">hi@darshana.io</p>
                            </div>
                        </div> {/*<!-- single contact info -->*/}
                    </div>
                    <div className="col-lg-4 col-md-6">
                        <div className="single-contact-info contact-color-3 mt-30 d-flex  wow fadeInUp align-items-center" data-wow-duration="1s" data-wow-delay="0.9s">
                            <div className="contact-info-icon">
                                <i className="lni-phone"> <img  src="img/discord.png" alt="discord" /></i>
                            </div>
                            <div className="contact-info-content media-body">
                                <a href="https://discord.gg/darshana" target="_blank"><p className="text">Join Discord</p></a>
                            </div>
                        </div> {/*<!-- single contact info -->*/}
                    </div>
                </div> {/*<!-- row -->*/}
            </div> {/*<!-- contact info -->*/}
            <div className="row">
                <div className="col-lg-12">
                    <div className="contact-wrapper-form pt-115  wow fadeInUpBig" data-wow-duration="1s" data-wow-delay="0.5s">
                        <h4 className="contact-title pb-10"><i className="lni-envelope"></i> Leave <span>A Message.</span></h4>
                        
                        <form id="contact-form" action="assets/contact.php" method="post">
                            <div className="row">
                                <div className="col-md-6">
                                    <div className="contact-form mt-45">
                                        <label>Enter Your Name</label>
                                        <input type="text" name="name" placeholder="Full Name"/>
                                    </div> {/*<!-- contact-form -->*/}
                                </div>
                                <div className="col-md-6">
                                    <div className="contact-form mt-45">
                                        <label>Enter Your Email</label>
                                        <input type="email" name="email" placeholder="Email"/>
                                    </div> {/*<!-- contact-form -->*/}
                                </div>
                                <div className="col-md-12">
                                    <div className="contact-form mt-45">
                                        <label>Your Message</label>
                                        <textarea name="message" placeholder="Enter your message..."></textarea>
                                    </div> {/*<!-- contact-form -->*/}
                                </div>
                                <p className="form-message"></p>
                                <div className="col-md-12">
                                    <div className="contact-form mt-45">
                                        <button type="submit" className="main-btn">Send Now</button>
                                    </div> {/*<!-- contact-form -->*/}
                                </div>
                            </div> {/*<!-- row -->*/}
                        </form>
                    </div> {/*<!-- contact wrapper form -->*/}
                </div>
            </div> {/*<!-- row -->*/}
        </div> {/*<!-- container -->*/}
    </section>

    {/*<!--====== CONTACT PART ENDS ======-->*/}
    
    {/*<!--====== FOOTER PART START ======-->*/}
    
    <footer id="footer" className="footer-area bg_cover">{/* style="background-image: url(assets/images/footer-bg.jpg)"*/}
        <div className="container">
            <div className="footer-widget pt-30 pb-70">
                <div className="row">
                    <div className="col-lg-3 col-sm-6 order-sm-1 order-lg-1">
                        <div className="footer-about pt-40">
                            <a href="#">
                                <img  src="img/dar-logo.png" alt="Logo" />
                            </a>
                            <p className="text">A new protocol using blockchain technology to validate identities and speed up the hiring process.</p>
                        </div> {/*<!-- footer about -->*/}
                    </div>
                    <div className="col-lg-3 col-sm-6 order-sm-3 order-lg-2">
                        <div className="footer-link pt-40">
                            <div className="footer-title">
                                <h5 className="title">Our profiles</h5>
                            </div>
                            <ul>
                                <li><a href="#">Talent looking for a job</a></li>
                                <li><a href="#">Companies hiring tech talent</a></li>
                                <li><a href="#">Tech Communities</a></li>
                            </ul>
                        </div> {/*<!-- footer link -->*/}
                    </div>
                    <div className="col-lg-3 col-sm-6 order-sm-4 order-lg-3">
                        <div className="footer-link pt-40">
                            <div className="footer-title">
                                <h5 className="title">About Us</h5>
                            </div>
                            <ul>
                                <li><a href="#">Awards & Recognitions</a></li>
                                <li><a href="#">Team</a></li>
                            </ul>
                        </div> {/*<!-- footer link -->*/}
                    </div>
                    <div className="col-lg-3 col-sm-6 order-sm-2 order-lg-4">
                        <div className="footer-contact pt-40">
                            <div className="footer-title">
                                <h5 className="title">Contact Info</h5>
                            </div>
                            <div className="contact pt-10">
                                <p className="text">90 Canal St <br/> Boston, MA 02114 <br/>USA</p>
                                <p className="text">hi@darshana.io</p>

                                <ul className="social mt-40">
                                    <li><a href="#"><i className="fa fa-facebook"></i></a></li>
                                    <li><a href="#"><i className="fa fa-twitter"></i></a></li>
                                    <li><a href="#"><i className="fa fa-instagram"></i></a></li>
                                    <li><a href="#"><i className="fa fa-linkedin"></i></a></li>
                                    {/*<li><a href="#"><i className="fa-brands fa-medium"></i></a></li>*/}
                                </ul>
                            </div> {/*<!-- contact -->*/}
                        </div> {/*<!-- footer contact -->*/}
                    </div>
                </div> {/*<!-- row -->*/}
            </div> {/*<!-- footer widget -->*/}
            <div className="footer-copyright text-center">
                <p className="text">© 2022 Crafted by Darshana All Rights Reserved.</p>
            </div>
        </div> {/*<!-- container -->*/}
    </footer>
    
    {/*<!--====== FOOTER PART ENDS ======-->*/}
    
    {/*<!--====== BACK TOP TOP PART START ======-->*/}

    <a href="https://api.whatsapp.com/send?phone=51982255435&text=Hi!%20I%20would%20like%20to%20schedule%20a%20demo%20for%20hiring%20tech%20talent.%20/%20Hola!%20Me%20gustar%C3%ADa%20agendar%20un%20demo%20para%20contratar%20talento%20tech."  className="whatsapp"><i className="fa fa-whatsapp"></i></a>

    {/*<!--====== BACK TOP TOP PART ENDS ======-->*/}  
  </body>
    </>
  )
}

export const getServerSideProps = async (context) => {
  const [benefitsRes, headerRes, talentRes, companyRes, communityRes, protocolRes, testimonialRes, partnershipRes] = await Promise.all([
    fetch("https://darshana.directus.app/items/benefits"),
    fetch("https://darshana.directus.app/items/header"),
    fetch("https://darshana.directus.app/items/talent_details"),
    fetch("https://darshana.directus.app/items/company_details"),
    fetch("https://darshana.directus.app/items/community_details"),
    fetch("https://darshana.directus.app/items/protocol"),
    fetch("https://darshana.directus.app/items/testimonials"),
    fetch("https://darshana.directus.app/items/partnerships")
  ]);

  const [benefits, header, talents, companies, communities, protocol, testimonials, partnerships] = await Promise.all([
    benefitsRes.json(),
    headerRes.json(),
    talentRes.json(),
    companyRes.json(),
    communityRes.json(),
    protocolRes.json(),
    testimonialRes.json(),
    partnershipRes.json(),
  ]);

  return { props: { 
    benefit: benefits,
    head: header,
    talent: talents,
    company:companies,
    community: communities,
    protocolDet: protocol,
    testimonial: testimonials,
    partnership: partnerships, 
  } };

}
